/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TypeOfThisLineRow =
  | "header"
  | "paragraph"
  | "code"
  | "item"
  | "row"
  | "gallery";
export type DefaultText = string;
export type ListOfTextDataForThisLineRow = (TextWithOptions | DefaultText)[];
export type NumberToSpecifyHeaderAndListDeepening = number;
export type LanguageNameToSuggestSpecificCodeHighlight = string;
export type CinnabarForgeTextMarkup = {
  type: TypeOfThisLineRow;
  data: ListOfTextDataForThisLineRow;
  level?: NumberToSpecifyHeaderAndListDeepening;
  codeLanguage?: LanguageNameToSuggestSpecificCodeHighlight;
}[];

export interface TextWithOptions {
  text: string;
  highlight?: "bold" | "italic" | "underline" | "code";
  glueLastText?: boolean;
  link?: string;
  glueLastLink?: boolean;
  mergeCellBelow?: boolean;
}
