// This file was generated by Cinnabar Forge Meta. Do not edit.

export default {
  "cinnabarMetaVersion": 1,
  "description": "A JSON-based text markup",
  "name": "Cinnabar Markup",
  "stack": {
    "nodejs": {
      "outputFile": [
        "src",
        "cinnabar.js"
      ],
      "package": "@cinnabar-forge/markup"
    }
  },
  "version": {
    "major": 0,
    "minor": 0,
    "patch": 0,
    "text": "0.0.0"
  }
};
